/*
    Generated by parsecsv.ts
    */
import { IScript } from "@koksmat/powerpacks";
import { z } from "zod";
import { sharedMailbox as itemClass } from "../schemas/dist";

const item = itemClass.view;
type targetType = z.infer<typeof item>;

const inputRecord = z.object({
  DisplayName: z
    .string()
    .trim()
    .openapi({ example: "Test d6c75a76-bb1e-4b10-828e-f143964228b3" }),
  Name: z
    .string()
    .trim()
    .openapi({ example: "test-d6c75a76-bb1e-4b10-828e-f143964228b3" }),
  MailTip: z.string().trim().openapi({ example: "" }),
  PrimarySmtpAddress: z
    .string()
    .trim()
    .openapi({
      example:
        "test-d6c75a76-bb1e-4b10-828e-f143964228b3@M365x65867376.onmicrosoft.com",
    }),
  WhenCreatedUTC: z.string().trim().openapi({ example: "03.04.2023 17:44:00" }),
  Alias: z
    .string()
    .trim()
    .openapi({ example: "test-d6c75a76-bb1e-4b10-828e-f143964228b3" }),
});

type inputType = z.infer<typeof inputRecord>;
export default class Script {
  static map(input: inputType, target: targetType): targetType {
    target.displayName = input.DisplayName;
    target.name = input.Name;
    //target.mailTip = input.MailTip
    target.primarySmtpAddress = input.PrimarySmtpAddress;
    //target.whenCreatedUTC = input.WhenCreatedUTC
    target.alias = input.Alias;

    return target;
  }
}
