import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex p-10'>
      <Link className='p-3' href={"/"}>Home</Link>
      <Link className='p-3' href={"/tests"}>Tests</Link>
      </div>
        <div> {children}</div>
       
        
        
        </body>
    </html>
  )
}
