import Header from '@/components-highlevel/Header'
import Layout from '@/components-highlevel/Layout';
import Link from 'next/link'
import './globals.css'
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Layout>
       
       
            <div className='flex p-10'>
              <Link className='p-3' href={"/"}>Home</Link>
              <Link className='p-3' href={"/tests"}>Tests</Link>
            </div>
            {children}

          </Layout>


        </NextAuthProvider>
      </body>
    </html>
  )
}
