import Header from '@/components-highlevel/Header'
import Layout from '@/components-highlevel/Layout';
import Link from 'next/link'
import './globals.css'
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
{children}


        </NextAuthProvider>
      </body>
    </html>
  )
}
