
    /*
    Generated by pack.ts
    */
import {IScript} from "@koksmat/powerpacks"


export interface IParameters {
  
}
export default class Script implements IScript{
  
  public get code() : string {
    return `# Connector: Exchange
# Commands: Get-Recipient 
$culture = [System.Globalization.CultureInfo]::CreateSpecificCulture("de-DE")


[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
[System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
Get-Recipient -ResultSize Unlimited |
    Select-Object -Property Name, PrimarySmtpAddress, RecipientType, RecipientTypeDetails, EmailAddresses,WhenCreatedUTC |
    Export-Csv -Path $PSScriptRoot/recipients.csv -NoTypeInformation -Encoding UTF8 -UseCulture
`
  }
  public get commands() : string[] {
    return ['Get-Recipient']
  }
}
    