
    /*
    Generated by pack.ts
    */
import {IScript} from "@koksmat/powerpacks"


export interface IParameters {
  
}
export default class Script implements IScript{
  
  public get code() : string {
    return `# Connector: Exchange
# Commands: Get-Mailbox


# This to ensure a predictalbe output of e.g. dates

$culture = [System.Globalization.CultureInfo]::CreateSpecificCulture("de-DE")
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture
[System.Threading.Thread]::CurrentThread.CurrentCulture = $culture

Get-Mailbox  -ResultSize Unlimited -RecipientTypeDetails SharedMailbox
     | Select-Object -Property DisplayName,Name,MailTip, PrimarySmtpAddress,WhenCreatedUTC, Alias
    | Export-Csv -Path $PSScriptRoot/sharedmailboxes.csv -NoTypeInformation -Encoding UTF8 -UseCulture
`
  }
  public get commands() : string[] {
    return ['Get-Mailbox']
  }
  public get outputFiles() : string[] {
    return []
  }

  mapPowerShellInput(input:IParameters) : string {
     return ``
}
get commandParameters() : string {
  return ``
}
}
    