/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/authorize": {
    /**
     * Authenticating app 
     * @description 
     * 
     * You need an ´appkey´  to access the API. The ´appkey´  is issue by [niels.johansen@nexigroup.com](mailto:niels.johansen@nexigroup.com).
     * 
     * Use the ´appkey´  to get an access token through the /v1/authorize end point. The access token is valid for 10 minutes.
     * 
     * Pass the access token in the Authorization header as a Bearer token to access the API.
     */
    post: operations["koksmat/restapi.signin"];
  };
  "/blob/{tag}": {
    /**
     * Reading blob 
     * @description 
     * 
     * 
     * Returns a piece of unstructured data
     */
    get: operations["koksmat/restapi.getBlob"];
  };
  "/v1/business/countries": {
    /** Get a country */
    get: operations["koksmat/restapi.getCountries"];
  };
  "/v1/business/units": {
    /** Get busines and group units */
    get: operations["koksmat/restapi.getBusinessAndGroupUnits"];
  };
  "/v1/info/": {
    /** Get runtime info */
    get: operations["koksmat/restapi.getInfo"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ModelBusinessGroupUnit: {
      /** Format: date-time */
      created_at?: string;
      id?: components["schemas"]["PrimitiveObjectID"];
      /** @example Finance */
      name?: string;
      /** @example finance */
      short?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    ModelCountry: {
      /** @example Sweden */
      Name?: string;
      /** @example SE */
      code?: string;
      /** Format: date-time */
      created_at?: string;
      id?: components["schemas"]["PrimitiveObjectID"];
      /** Format: date-time */
      updated_at?: string;
    };
    PrimitiveObjectID: (number)[] | null;
    RestErrResponse: {
      /** @description Application-specific error code. */
      code?: number;
      /** @description Application context. */
      context?: {
        [key: string]: unknown;
      };
      /** @description Error message. */
      error?: string;
      /** @description Status text. */
      status?: string;
    };
    RestapiBlobResponse: {
      content?: {
        [key: string]: unknown;
      } | null;
    };
    RestapiGetResponse: {
      countries?: (components["schemas"]["ModelCountry"])[] | null;
    };
    RestapiGetResponseType2: {
      units?: (components["schemas"]["ModelBusinessGroupUnit"])[] | null;
    };
    RestapiInfoResponse: {
      exchange_organisation?: string;
      tenant?: string;
      version?: string;
    };
    RestapiSigninRequest: {
      appkey?: string;
    };
    RestapiSigninResponse: {
      token?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /**
   * Authenticating app 
   * @description 
   * 
   * You need an ´appkey´  to access the API. The ´appkey´  is issue by [niels.johansen@nexigroup.com](mailto:niels.johansen@nexigroup.com).
   * 
   * Use the ´appkey´  to get an access token through the /v1/authorize end point. The access token is valid for 10 minutes.
   * 
   * Pass the access token in the Authorization header as a Bearer token to access the API.
   */
  "koksmat/restapi.signin": {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["RestapiSigninRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RestapiSigninResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
    };
  };
  /**
   * Reading blob 
   * @description 
   * 
   * 
   * Returns a piece of unstructured data
   */
  "koksmat/restapi.getBlob": {
    parameters: {
      path: {
        tag: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          "Cache-Control"?: string;
        };
        content: {
          "application/json": components["schemas"]["RestapiBlobResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
    };
  };
  /** Get a country */
  "koksmat/restapi.getCountries": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RestapiGetResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
    };
  };
  /** Get busines and group units */
  "koksmat/restapi.getBusinessAndGroupUnits": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RestapiGetResponseType2"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
    };
  };
  /** Get runtime info */
  "koksmat/restapi.getInfo": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RestapiInfoResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["RestErrResponse"];
        };
      };
    };
  };
}
