
    /*
    Generated by pack.ts
    */
import {IScript} from "@koksmat/powerpacks"


export interface IParameters {
  name : string,capacity : any,prefix : string
}
export default class Script implements IScript{
  
  public get code() : string {
    return `# Connector: Exchange
# Commands: New-Mailbox
param (
    [Parameter(Mandatory = $true)]
    [string]$Name,
    [Parameter(Mandatory = $true)]
    [int]$capacity,
 
    [string]$prefix

 
   
)

$alias = $name.Split("(")[0].Trim().Replace(" ", "-").ToLower()
$mailbox = New-Mailbox -Name ($prefix + "room-$alias") -DisplayName "$name" -Room -ResourceCapacity  $capacity

        
write-output $mailbox.WindowsEmailAddress`
  }
  public get commands() : string[] {
    return ['New-Mailbox']
  }
  public get outputFiles() : string[] {
    return []
  }

  mapPowerShellInput(input:IParameters) : string {
     return `$Name = "${input.name}" 
$capacity = "${input.capacity}" 
$prefix = "${input.prefix}" `
}
get commandParameters() : string {
  return `-Name  $Name -capacity  $capacity -prefix  $prefix`
}
}
    